<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 * Provides a person entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function plentific_demo_theme(): array {
  return [
    'person' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for person templates.
 *
 * Default template: person.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the person information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_person(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
