block.settings.plentific_demo_plentific_api:
  type: block_settings
  label: 'Plentific API block'
  mapping:
    number_of_items_per_page:
      type: integer
      label: The no. of items per page in the user list view
    email_field_label:
      type: string
      label: The column heading in the user list view
    forename_field_label:
      type: string
      label: The column heading in the user list view
    surname_field_label:
      type: string
      label: The column heading in the user list view

plentific_demo.importer.*:
  type: config_entity
  label: Importer
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    url:
      type: uri
      label: Uri
    plugin:
      type: string
      label: Plugin ID
    update_existing:
      type: boolean
      label: Whether to update existing users
    bundle:
      type: string
      label: The person bundle
