block.settings.plentific_demo_plentific_api:
  type: block_settings
  label: 'Plentific API block'
  mapping:
    number_of_items_per_page:
      type: integer
      label: The no. of items per page in the user list view
    email_field_label:
      type: string
      label: The column heading in the user list view
    forename_field_label:
      type: string
      label: The column heading in the user list view
    surname_field_label:
      type: string
      label: The column heading in the user list view

plentific_demo.importer.*:
  type: config_entity
  label: 'Importer config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: uri
      label: Uri
    plugin:
      type: string
      label: Plugin ID
    update_existing:
      type: boolean
      label: Whether to update existing persons
    bundle:
      type: string
      label: The person bundle

plentific_demo.person_type.*:
  type: config_entity
  label: 'Person type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
